version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: Phase_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: Phase_2
      DB_USER: postgres
      DB_PASSWORD: pass
      DB_HOST: db
      DB_PORT: 5432
